(()=>{
      const $=id=>document.getElementById(id), ascii=s=>{for(let i=0;i<s.length;i++)if(s.charCodeAt(i)<32||s.charCodeAt(i)>126)return false;return true}, toHex=n=>n.toString(16).padStart(2,'0').toUpperCase(), bytesHex=a=>a.map(toHex).join(' '), xor=(a,b)=>a.map((v,i)=>v^b[i]);
      function renderSteps(target, left, key, result, mode){if(!left.length){target.innerHTML='<div class="empty-state">Tidak ada langkah untuk ditampilkan.</div>';return}const bits=n=>n.toString(2).padStart(8,'0');let rows=left.map((v,i)=>`<tr><td>${i+1}</td><td>${mode==='enc'?esc(String.fromCharCode(v)):toHex(v)}</td><td>${toHex(v)}<br><small>${bits(v)}</small></td><td>${esc(key[i])}</td><td>${toHex(key.charCodeAt(i))}<br><small>${bits(key.charCodeAt(i))}</small></td><td>${bits(result[i])}</td><td>${toHex(result[i])}</td></tr>`).join('');target.innerHTML=`<table><thead><tr><th>#</th><th>${mode==='enc'?'Plain':'Cipher'}</th><th>Byte A</th><th>Key</th><th>Byte B</th><th>Bit hasil XOR</th><th>Hasil</th></tr></thead><tbody>${rows}</tbody></table>`}
      function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
      function msg(id,text,type=''){const el=$(id);el.textContent=text;el.className='message'+(type?' '+type:'')}
      function validPair(a,k,label){if(!a.length)return `Masukkan ${label}.`;if(!k.length)return 'Masukkan keystream.';if(!ascii(a)||!ascii(k))return 'Gunakan karakter ASCII cetak saja (kode 32–126).';if(a.length!==k.length)return `Panjang ${label.toLowerCase()} (${a.length}) dan keystream (${k.length}) harus sama.`;return ''}
      document.querySelectorAll('.nav [data-view]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.view;document.querySelectorAll('.nav [data-view]').forEach(item=>item.setAttribute('aria-selected',item===button?'true':'false'));document.querySelectorAll('.view-panel').forEach(panel=>panel.classList.toggle('active',panel.id===id));}));
      function openView(id){const button=document.querySelector(`.nav [data-view="${id}"]`);if(button)button.click()}
      $('plain').addEventListener('input',()=> $('plain-count').textContent=$('plain').value.length+' karakter');$('stream').addEventListener('input',()=> $('stream-count').textContent=$('stream').value.length+' karakter');$('dec-stream').addEventListener('input',()=> $('dec-stream-count').textContent=$('dec-stream').value.length+' karakter');
      $('fill-example').addEventListener('click',()=>{$('plain').value='HELLO';$('stream').value='ABCDE';$('plain').dispatchEvent(new Event('input'));$('stream').dispatchEvent(new Event('input'));$('encrypt-btn').click()});
      $('send-to-decrypt').addEventListener('click',()=>{if($('enc-result').textContent==='—'){$('encrypt-btn').click();if($('enc-result').textContent==='—')return}$('cipher-input').value=$('enc-result').textContent;$('dec-stream').value=$('stream').value;$('dec-stream').dispatchEvent(new Event('input'));openView('dec-panel')});
      $('encrypt-btn').addEventListener('click',()=>{let p=$('plain').value,k=$('stream').value,e=validPair(p,k,'plaintext');if(e){msg('enc-message','❌ '+e,'error');return}let a=[...p].map(c=>c.charCodeAt(0)),b=[...k].map(c=>c.charCodeAt(0)),c=xor(a,b);$('enc-result').textContent=bytesHex(c)||'—';renderSteps($('enc-steps'),a,k,c,'enc');msg('enc-message','✓ Enkripsi berhasil.','success')});
      $('decrypt-btn').addEventListener('click',()=>{let raw=$('cipher-input').value.trim(),k=$('dec-stream').value;if(!raw){msg('dec-message','❌ Masukkan ciphertext heksadesimal.','error');return}let compact=raw.replace(/[\s,]/g,'');if(!/^(?:[0-9a-fA-F]{2})+$/.test(compact)){msg('dec-message','❌ Format salah. Masukkan pasangan digit hex, misalnya 09 07 0F.','error');return}let a=compact.match(/.{2}/g).map(x=>parseInt(x,16));if(!k.length){msg('dec-message','❌ Masukkan keystream.','error');return}if(!ascii(k)){msg('dec-message','❌ Gunakan keystream ASCII cetak saja (kode 32–126).','error');return}if(a.length!==k.length){msg('dec-message',`❌ Jumlah byte ciphertext (${a.length}) dan panjang keystream (${k.length}) harus sama.`,'error');return}let b=[...k].map(c=>c.charCodeAt(0)),p=xor(a,b);if(p.some(v=>v<32||v>126)){msg('dec-message','❌ Hasil bukan teks ASCII cetak yang dapat ditampilkan. Periksa keystream.','error');return}$('dec-result').textContent=String.fromCharCode(...p)||'—';renderSteps($('dec-steps'),a,k,p,'dec');msg('dec-message','✓ Dekripsi berhasil.','success')});
      $('copy-cipher').addEventListener('click',()=>copy($('enc-result').textContent));$('copy-plain').addEventListener('click',()=>copy($('dec-result').textContent));async function copy(s){if(!s||s==='—')return;try{await navigator.clipboard.writeText(s)}catch{const t=document.createElement('textarea');t.value=s;document.body.append(t);t.select();document.execCommand('copy');t.remove()}}
      function pad(s,n){return s.padEnd(n,' ')}function reuse(){let p1=$('msg-one').value,p2=$('msg-two').value,k=$('reuse-key').value;if(!p1.length||!p2.length||!k.length){msg('reuse-message','❌ Isi kedua pesan dan keystream.','error');return}if(!ascii(p1)||!ascii(p2)||!ascii(k)){msg('reuse-message','❌ Gunakan karakter ASCII saja.','error');return}let n=Math.max(p1.length,p2.length);if(k.length<n){msg('reuse-message',`❌ Keystream minimal ${n} karakter agar dapat mengenkripsi kedua pesan.`,'error');return}if(k.length>n)k=k.slice(0,n);p1=pad(p1,n);p2=pad(p2,n);let a=xor([...p1].map(c=>c.charCodeAt(0)),[...k].map(c=>c.charCodeAt(0))),b=xor([...p2].map(c=>c.charCodeAt(0)),[...k].map(c=>c.charCodeAt(0))),d=xor(a,b),known=xor([...p1].map(c=>c.charCodeAt(0)),[...p2].map(c=>c.charCodeAt(0)));$('c1').textContent=bytesHex(a);$('c2').textContent=bytesHex(b);$('reuse-xor').textContent=bytesHex(d);$('reuse-ascii').textContent='ASCII hasil XOR plaintext: '+[...known].map(x=>x>=32&&x<=126?String.fromCharCode(x):'·').join('');msg('reuse-message','✓ Ciphertext 1 ⊕ ciphertext 2 sama dengan plaintext 1 ⊕ plaintext 2.','success')}
      $('reuse-btn').addEventListener('click',reuse);reuse();
      const cases=[{name:'Pesan 3 karakter',plain:'CAT',key:'DOG',expected:'07 0E 13'},{name:'Pesan 4 karakter',plain:'MEET',key:'KEYS',expected:'06 00 1C 07'},{name:'Pesan 4 karakter',plain:'DATA',key:'MASK',expected:'09 00 07 0A'}];
      $('test-list').innerHTML=cases.map((t,i)=>`<div class="test-row"><div class="test-name"><strong>Test ${i+1} · ${t.name}</strong><small>Plaintext: ${esc(t.plain)} · Keystream: ${esc(t.key)}</small></div><div><small>Output aktual</small><code id="actual-${i}">—</code></div><div><small>Expected output</small><code>${t.expected}</code></div><span class="badge" id="badge-${i}">BELUM DIUJI</span></div>`).join('');
      $('run-tests').addEventListener('click',()=>{let passed=0;cases.forEach((t,i)=>{let actual=bytesHex(xor([...t.plain].map(c=>c.charCodeAt(0)),[...t.key].map(c=>c.charCodeAt(0))));let ok=actual===t.expected;$(`actual-${i}`).textContent=actual;let b=$(`badge-${i}`);b.textContent=ok?'PASS':'FAIL';b.className='badge '+(ok?'pass':'fail');if(ok)passed++});$('test-summary').textContent=`${passed} dari ${cases.length} test lulus.`});
    })();
